name: Simple

# Controls when the workflow will run
on: [push]

defaults:
  run:
    shell: pwsh

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: |
          Get-Module -ListAvailable
