name: Publish [GitHub.ServerStatistics]

on:
  push:
    paths:
    - scripts/**
    - src/GitHub.ServerStatistics/**
    - .github/workflows/Publish.GitHub.ServerStatistics.yml
  workflow_dispatch:

defaults:
  run:
    shell: pwsh

env:
  ModuleName: 'GitHub.ServerStatistics'
  APIKey: ${{ secrets.apikey }}

jobs:
  publish:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Publish module
        run: |
          .\scripts\Publish-Module.ps1 -ModuleName $env:ModuleName -APIKey $env:APIKey -Verbose
