name: Publish Module

on:
  push:
    paths:
    - src/GitHub/**
    - .github/workflows/publish.yml

defaults:
  run:
    shell: pwsh

env:
  APIKey: ${{ secrets.apikey }}

jobs:
  publish:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install chained modules
        run: |
          Find-Module -Name GitHub* | Where-Object CompanyName -eq MariusStorhaug | Install-Module -Force

      - name: Bump version
        run: |
          .\scripts\Set-ModuleVersion.ps1 -ModuleName GitHub -Verbose

      - name: Publish module
        run: |
          Publish-Module -Path 'src/GitHub' -NuGetApiKey "$env:APIKey" -Verbose
