name: Publish [GitHub.Core]

on:
  push:
    paths:
    - src/GitHub.Core/**
    - .github/workflows/Publish.GitHub.Core.yml

defaults:
  run:
    shell: pwsh

env:
  ModuleName: 'GitHub.Core'
  APIKey: ${{ secrets.apikey }}

jobs:
  publish:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Publish module
        run: |
          $Info = Invoke-Expression (Get-Content .\src\$env:ModuleName\$env:ModuleName.psd1 -Raw)
          $Info.RequiredModules | % {
            Install-Module -Name $_.ModuleName -Force -Verbose
          }

          .\scripts\Set-ModuleVersion.ps1 -ModuleName $env:ModuleName -Verbose
          Publish-Module -Path "src/$env:ModuleName" -NuGetApiKey "$env:APIKey" -Verbose
