name: Publish Module

on:
  push:
    paths:
    - src\GitHub\**
    - .github\workflows\publish.yml

defaults:
  run:
    shell: pwsh

env:
  APIKey: ${{ secrets.apikey }}

jobs:
  publish:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2
      - run: |
          Publish-Module -Path 'src\GitHub' -NuGetApiKey "$env:APIKey" -Verbose
