name: Publish [GitHub.Deployments]

on:
  push:
    paths:
    - src/GitHub.Deployments/**
    - .github/workflows/Publish.GitHub.Deployments.yml
  workflow_dispatch:

defaults:
  run:
    shell: pwsh

env:
  ModuleName: 'GitHub.Deployments'
  APIKey: ${{ secrets.apikey }}

jobs:
  publish:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Publish module
        run: |
          .\scripts\Publish-Module.ps1 -ModuleName $env:ModuleName -APIKey $env:APIKey -Verbose
