name: Publish [GitHub]

on:
  push:
    paths:
    - scripts/**
    - src/GitHub/**
    - .github/workflows/Publish.GitHub.yml
  workflow_dispatch:

defaults:
  run:
    shell: pwsh

env:
  ModuleName: 'GitHub'
  APIKey: ${{ secrets.apikey }}

jobs:
  publish:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Add 'src' to path
        run: |
          $SRCPath = Get-Item -Path .\src\ | Select-Object -ExpandProperty FullName
          $env:Path += ";$SRCPath"

      - name: Check Path
        run: |
          $env:Path -Split ';'

      - name: Publish module
        run: |
          .\scripts\Publish-Module.ps1 -ModuleName $env:ModuleName -APIKey $env:APIKey -Verbose
