name: Publish [GitHub.Licenses]

on:
  push:
    paths:
    - src/GitHub.Licenses/**
    - .github/workflows/Publish.GitHub.Licenses.yml

defaults:
  run:
    shell: pwsh

env:
  ModuleName: 'GitHub.Licenses'
  APIKey: ${{ secrets.apikey }}

jobs:
  publish:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Publish module
        run: |
          $Info = Invoke-Expression (Get-Content .\src\$env:ModuleName\$env:ModuleName.psd1 -Raw)
          foreach ($Module in $Info.RequiredModules) {
            Write-Verbose "Install module: $($Module.ModuleName)"
            Install-Module -Name $Module.ModuleName -Force -Verbose
          }

          .\scripts\Set-ModuleVersion.ps1 -ModuleName $env:ModuleName -Verbose
          Publish-Module -Path "src/$env:ModuleName" -NuGetApiKey "$env:APIKey" -Verbose

